name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: "8.3"
            moodle-branch: "MOODLE_405_STABLE"
            database: pgsql

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql, intl, zip, xml, dom, mbstring, curl, json
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install Moodle with dependencies
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
          cd moodle
          mkdir -p admin/tool mod
          git clone --depth 1 --branch ${{ matrix.moodle-branch }} https://github.com/pavel-pasechnik/moodle-tool_certificate.git admin/tool/certificate
          git clone --depth 1 --branch ${{ matrix.moodle-branch }} https://github.com/pavel-pasechnik/moodle-mod_coursecertificate.git mod/coursecertificate
          php admin/cli/upgrade.php --non-interactive --allow-unstable
        env:
          DB: pgsql
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint --plugin ./plugin

      - name: PHP Mess Detector
        continue-on-error: true
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpmd --plugin ./plugin

      - name: Code checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcs --plugin ./plugin --max-warnings 0

      - name: PHPDoc checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpdoc --plugin ./plugin --max-warnings 0

      - name: Validate plugin
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate --plugin ./plugin

      - name: Check upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints --plugin ./plugin

      - name: Mustache Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci mustache --plugin ./plugin

      - name: Grunt build
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci grunt --plugin ./plugin --max-lint-warnings 0

      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit --plugin ./plugin --fail-on-warning --coverage-text

      - name: Behat tests
        id: behat
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci behat --plugin ./plugin --profile chrome --scss-deprecations

      - name: Upload Behat failures
        if: ${{ failure() && steps.behat.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: Behat failures (${{ join(matrix.*, ', ') }})
          path: ${{ github.workspace }}/moodledata/behat_dump
          retention-days: 7
          if-no-files-found: ignore

      - name: Package and release (only on main)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          cd moodle/admin/tool/certificate/element
          zip -r ../../../certificateelement_autonumber.zip autonumber
          TAG="v$(date +'%Y.%m.%d.%H%M')"
          gh release create "$TAG" ../../../certificateelement_autonumber.zip -t "Release $TAG" -n "Automated CI release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
