name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Moodle and move plugin
        env:
          PGPASSWORD: moodle
        run: |
          export PATH="$(pwd)/ci/bin:$PATH"
          # Очистка старой Moodle-папки
          rm -rf moodle
          mkdir -p moodle/admin/tool/certificate
          mkdir -p moodle/mod

          # Клонируем стабильные версии форков Павла
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-tool_certificate.git moodle/admin/tool/certificate
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-mod_coursecertificate.git moodle/mod/coursecertificate

          # Установка Moodle
          moodle-plugin-ci install \
            --db-type=pgsql \
            --db-user=moodle \
            --db-pass=moodle \
            --db-name=moodle \
            --branch=main

          # Перенос сабплагина
          mkdir -p moodle/admin/tool/certificate/element/autonumber
          rsync -av --exclude 'moodle' --exclude '.git' --exclude 'ci' --exclude 'admin/recalculate.php' ./ moodle/admin/tool/certificate/element/autonumber/
          cp admin/recalculate.php moodle/admin/tool/certificate/element/autonumber/recalculate.php
          rm -rf admin

      - name: Generate next tag
        id: tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          IFS='.' read -r -a PARTS <<< "${LAST_TAG#v}"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}
          NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "Next tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_OUTPUT
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"

      - name: Create plugin archive
        run: |
          cd moodle/admin/tool/certificate/element
          zip -r ../../../certificateelement_autonumber.zip autonumber

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: certificateelement_autonumber
          path: moodle/admin/tool/certificateelement_autonumber.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "Autonumber for Moodle Certificates ${{ steps.tag.outputs.tag }}"
          tag_name: ${{ steps.tag.outputs.tag }}
          body_path: CHANGELOG.md
          files: moodle/admin/tool/certificateelement_autonumber.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
