name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: moodle
          POSTGRES_PASSWORD: moodle
          POSTGRES_DB: moodle
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U moodle"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pgsql, intl, zip, xml, dom, mbstring, curl, json
          tools: composer, phpunit

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev moodlehq/moodle-plugin-ci ci
          export PATH="$(pwd)/ci/bin:$PATH"
          echo "$PATH"

      - name: Install Moodle core
        env:
          PGPASSWORD: moodle
        run: |
          export PATH="$(pwd)/ci/bin:$PATH"
          # Очистка старой базы, если уже существует
          psql -U moodle -h 127.0.0.1 -d postgres -c 'DROP DATABASE IF EXISTS moodle;'

          # Установка чистого Moodle без плагинов
          moodle-plugin-ci install \
            --db-type=pgsql \
            --db-host=127.0.0.1 \
            --db-port=5432 \
            --db-user=moodle \
            --db-pass=moodle \
            --db-name=moodle \
            --branch=main

      - name: Install Workplace plugins
        run: |
          cd moodle
          mkdir -p admin/tool mod
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-tool_certificate.git admin/tool/certificate
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-mod_coursecertificate.git mod/coursecertificate

      - name: Copy subplugin and upgrade Moodle
        run: |
          cd moodle
          mkdir -p admin/tool/certificate/element/autonumber
          rsync -av --exclude 'moodle' --exclude '.git' --exclude 'ci' ../ admin/tool/certificate/element/autonumber/
          php admin/cli/upgrade.php --non-interactive --allow-unstable

      - name: Initialise PHPUnit environment
        run: |
          cd moodle
          php admin/tool/phpunit/cli/init.php

      - name: Run Moodle PHPUnit tests
        run: |
          export PATH="$(pwd)/ci/bin:$PATH"
          moodle-plugin-ci phpunit

      - name: Generate next tag
        id: tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          IFS='.' read -r -a PARTS <<< "${LAST_TAG#v}"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}
          NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "Next tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_OUTPUT
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"

      - name: Create plugin archive
        run: |
          cd moodle/admin/tool/certificate/element
          zip -r ../../../certificateelement_autonumber.zip autonumber

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: certificateelement_autonumber
          path: moodle/admin/tool/certificateelement_autonumber.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "Autonumber for Moodle Certificates ${{ steps.tag.outputs.tag }}"
          tag_name: ${{ steps.tag.outputs.tag }}
          body_path: CHANGELOG.md
          files: moodle/admin/tool/certificateelement_autonumber.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
