name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Moodle and move plugin
        env:
          PGPASSWORD: moodle
        run: |
          export PATH="$(pwd)/ci/bin:$PATH"
          # Очистка старой Moodle-папки
          rm -rf moodle
          mkdir -p moodle/admin/tool/certificate
          mkdir -p moodle/mod

          # Клонируем стабильные версии форков Павла
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-tool_certificate.git moodle/admin/tool/certificate
          git clone --depth 1 --branch MOODLE_400_STABLE https://github.com/pavel-pasechnik/moodle-mod_coursecertificate.git moodle/mod/coursecertificate

          # Установка Moodle
          moodle-plugin-ci install \
            --db-type=pgsql \
            --db-user=moodle \
            --db-pass=moodle \
            --db-name=moodle \
            --branch=main

          # Перенос сабплагина
          mkdir -p moodle/admin/tool/certificate/element/autonumber
          rsync -av --exclude 'moodle' --exclude '.git' --exclude 'ci' --exclude 'admin/recalculate.php' ./ moodle/admin/tool/certificate/element/autonumber/
          cp admin/recalculate.php moodle/admin/tool/certificate/element/autonumber/recalculate.php
          rm -rf admin
